# Generated by Django 5.1.4 on 2025-03-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('Full-Time', 'Full Time'), ('Part-Time', 'Part Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=100),
        ),
    ]
