# Generated by Django 5.1.4 on 2025-03-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
