# Generated by Django 5.1.4 on 2025-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_season_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
