# Generated by Django 5.1.4 on 2025-03-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
