# Generated by Django 5.1.4 on 2025-03-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('employees', '0001_initial'),
        ('rooms', '0001_initial'),
        ('seasons', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0002_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('part_of_day', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='branches.branch')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='subjects.level')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='rooms.room')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='seasons.season')),
                ('students', models.ManyToManyField(related_name='groups', to='students.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='employees.employee')),
            ],
        ),
    ]
