# Generated by Django 5.1.4 on 2025-03-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_week_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='week_days',
            field=models.CharField(max_length=100),
        ),
    ]
