# Generated by Django 5.1.4 on 2025-03-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_week_days'),
        ('subjects', '0002_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject'),
        ),
    ]
