# Generated by Django 5.1.4 on 2025-03-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='language',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
