# Generated by Django 5.1.4 on 2025-03-14 17:42

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_language'),
        ('subjects', '0002_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Russian', 'Russian'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Turkish', 'Turkish'), ('Arabic', 'Arabic'), ('Hindi', 'Hindi'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese'), ('Dutch', 'Dutch'), ('Swedish', 'Swedish'), ('Polish', 'Polish'), ('Ukrainian', 'Ukrainian'), ('Greek', 'Greek'), ('Hebrew', 'Hebrew'), ('Persian', 'Persian'), ('Turkmen', 'Turkmen')], max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject'),
        ),
    ]
