# Generated by Django 5.1.4 on 2025-03-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_language_alter_group_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
