# Generated by Django 5.1.4 on 2025-03-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_deleted_at'),
        ('subjects', '0003_level_deleted_at_subject_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='subjects.level'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
