# Generated by Django 5.1.4 on 2025-03-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_level_alter_group_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subject',
        ),
    ]
